### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by WenchaoD** [f33chobits/FSMediaPicker#1]
![fsmediapicker-edit](https://cloud.githubusercontent.com/assets/5186464/6525012/1544d590-c43b-11e4-8ed2-8cf8eef14009.gif)
![fsmediapicker-circular-edited](https://cloud.githubusercontent.com/assets/5186464/6524931/11bfd51a-c43a-11e4-8197-ced99a29df69.gif)
![fsmediapicker-type-video](https://cloud.githubusercontent.com/assets/5186464/6525055/b20b75be-c43b-11e4-93eb-a0297157dd79.png)
![fsmediapicker-type-all](https://cloud.githubusercontent.com/assets/5186464/6525058/bc2e6736-c43b-11e4-811c-5d3f3ba82e26.png)
![localization](https://cloud.githubusercontent.com/assets/5186464/6525144/dba46592-c43c-11e4-8115-d4f17e382d43.png)
![fsmediapicker-chinese](https://cloud.githubusercontent.com/assets/5186464/6525153/0de85dec-c43d-11e4-9b73-298bd2fa9b9a.png)

**Comment by f33chobits** [comment]
![fsmediapicker-circular-edited](https://cloud.githubusercontent.com/assets/5186464/6524931/11bfd51a-c43a-11e4-8197-ced99a29df69.gif)
