### ISSUE TITLE
你好，如果不想用裁剪功能的话，要怎么设置呢

### ISSUE THREAD

**Issue by kakashilw** [f33chobits/FSMediaPicker#3]
我看源码包含默认和圆形裁剪，如果不想使用裁剪功能的话，要如何设置呢？

**Comment by WenchaoD** [comment]
我会增加一个设置，在这之前先使用，imagePicker.allowsEditing = NO吧  imagePicker指的是源码中的UIImagePickerController对象

**Comment by WenchaoD** [comment]
好了，现在设置mediaPicker.editMode = FSEditModeNone就可以禁掉裁剪，禁掉后取图片的时候要取`originalImage`，不要取裁剪后的图片`editedImage`。感谢提交issue~

**Comment by kakashilw** [comment]
好的，十分感谢提供这么好用的lib。。 另，用暴走表情写文档的风格很赞哇~~！！

**Comment by WenchaoD** [comment]
多谢夸奖啊:)
